### ISSUE TITLE
Week 7 Review Ticket

### ISSUE THREAD

**Issue by arushi10** [arushi10/individual#8]
**Total Score: 
Crossover:**

- [ ] [Review ticket with study plan and study reflection for week](https://github.com/arushi10/individual/issues/7)
Comments: 
- [ ] [Finals-Quiz1 score/50 and corrections](https://arushi10.github.io/individual/test_prep)
Comments:
- [ ] [Finals-Quiz2 score/50 and corrections](https://arushi10.github.io/individual/test_prep)
Comments:
- [ ] [Create Task code/runtime and 1 min video](https://arushi10.github.io/individual/create_task)
Comments:
- [ ] [Review ticket with Crossover Score](https://github.com/Gennalynb123/Individual-Algorithmic-Project/issues/8)
Comments:

**Comment by Gennalynb123** [comment]
CB: Gennalyn Bongolan

- [ ] [Start review ticket with study plan and study reflection for week](https://github.com/arushi10/individual/issues/7), due EOD Monday 4/18
- [ ] [Finals-Quiz1 score/50 and corrections](https://arushi10.github.io/individual/test_prep)
- [ ] [Finals-Quiz2 score/50 and corrections](https://arushi10.github.io/individual/test_prep)
- [ ] [Create Task code/runtime](https://arushi10.github.io/individual/create_task) and 1 min video are reviewed by another person, you may request Teacher review as time permits
- [ ] [Review ticket with Crossover Score](https://github.com/Gennalynb123/Individual-Algorithmic-Project/issues/8) on Monday 4/25 in class
